name: Build GUI - Web

on:
  push:
    branches:
      - main
    paths:
      - 'web_gui/**'
  workflow_dispatch:

jobs:
  deploy-gui:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./web_gui

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
